version: '2.2'

services:
    wsjtx:
        #build: .
        image: docker.pkg.github.com/8ch9azbsfifz/docker-wsjtx/wsjtx:0.1
        privileged: true
        volumes:
            - /dev/bus/usb:/dev/bus/usb
            - ./WSJT-X.ini:/root/.config/WSJT-X.ini
        ports:
            - 8081:8080
            - 2237:2237/udp
